- name: Replace line in file examples
  hosts: web
  handlers:
    - name: restart apache
      become: yes
      become_user: root
      service: name=httpd state=restarted
  tasks:
    - name: "Replacing the Ansible in the content to hostname with underline"
      become: yes
      become_user: root
      replace: 
        path: /var/www/default/index.html
        regexp: 'Hello, [A|a]nisble'
        replace: 'test'
        backup: yes
      notify: restart apache
